name: Main test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nim:
        - 1.4.8
        - 2.0.2
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: |
          nimble test -Y
          nimble refresh
